# Generated by Django 2.0.3 on 2020-06-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx_text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatfCx_xu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bglx', models.CharField(blank=True, max_length=30, null=True)),
                ('jy', models.CharField(blank=True, max_length=30, null=True)),
                ('cjzb', models.CharField(blank=True, max_length=30, null=True)),
                ('gj', models.CharField(blank=True, max_length=30, null=True)),
                ('pj', models.CharField(blank=True, max_length=30, null=True)),
                ('pgyw', models.CharField(blank=True, max_length=512, null=True)),
                ('pjnr', models.CharField(blank=True, max_length=1024, null=True)),
                ('bzh', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
