# Generated by Django 2.0.3 on 2020-06-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx_text', '0002_fatfcx_xu'),
    ]

    operations = [
        migrations.CreateModel(
            name='kk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
            ],
        ),
    ]
