# Generated by Django 2.0.3 on 2020-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx_text', '0003_kk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatfCx_xu1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bglx', models.CharField(blank=True, max_length=30, null=True)),
                ('jy', models.CharField(blank=True, max_length=30, null=True)),
                ('cjzb', models.CharField(blank=True, max_length=30, null=True)),
                ('gj', models.CharField(blank=True, max_length=30, null=True)),
                ('pj', models.CharField(blank=True, max_length=30, null=True)),
                ('pgyw', models.TextField(blank=True, null=True)),
                ('pjnr', models.TextField(blank=True, null=True)),
                ('bzh', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fatfcx_xu',
            name='pgyw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatfcx_xu',
            name='pjnr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
